title: "[Proposta] "
labels: [Proposta]
body:
  - type: textarea
    id: status
    attributes:
      label: Status
      description: "Qual é o status deste documento? (ex.: Proposta, Aceito, Rejeitado, Descontinuado, Suplantado)"
      value: 
      render: markdown
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Conteudo
      value: 
      render: markdown
